spring:
    profiles:
    active:
    - dev
---
spring:
    profiles: dev 
    application:
        name: micorservicecloud-config-zhi-dev
---
spring:
    profiles: test 
    application:
        name: micorservicecloud-config-zhi-test