server:
  port: 8889

spring:
  profiles: dev
  application:
    name: microservicecloud-config-client
  rabbitmq:
    host: 39.105.90.155
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
foo: JackMa
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
---
server:
  port: 8890
spring:
  profiles: test
  application:
    name: microservicecloud-config-client
foo: JackMa