spring: 
  profiles: 
    active: 
    - dev
---

server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.zhi.springcloud.entities       # 所有Entity别名类所在包
  mapper-locations:
  - mybatis/mapper/**/*.xml                # mapper映射文件

spring:
   profiles: dev 
   application:
    name: provider
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource             # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://39.105.90.155:3306/sc1                 # 数据库名称
    username: root
    password: WYZ980417
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                 # 等待连接获取的最大超时时间
eureka:
  client:   #指客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: provider1
    prefer-ip-address: true

info:
  app.name: xiaozhizhi
  company.name: 小智智有限公司
  build.artifact: $project.artifactId$
  build.version: $project.version$
