server:
  port: 8003

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: trip-service-8083

spring:
  application:
    profiles: dev
    name: trip-service