spring: 
  profiles: 
    active: 
    - dev
    
---
server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: user-route-data-service-8084
    prefer-ip-address: true
spring:
  application:
    profiles: dev
    name: user-route-data-service
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis